apiVersion: ray.io/v1
kind: RayCluster
metadata:
  name: ray-cluster
  namespace: default
spec:
  rayVersion: '2.8.0'
  headGroupSpec:
    serviceType: NodePort
    replicas: 1
    rayStartParams:
      dashboard-host: '0.0.0.0'
    template:
      spec:
        containers:
        - name: ray-head
          image: rayproject/ray:2.8.0-py310
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
          volumeMounts:
          - name: script-volume
            mountPath: /app
        volumes:
        - name: script-volume
          configMap:
            name: churn-processing-script

  workerGroupSpecs:
  - replicas: 2
    minReplicas: 1
    maxReplicas: 3
    groupName: worker-group
    rayStartParams: {}
    template:
      spec:
        containers:
        - name: ray-worker
          image: rayproject/ray:2.8.0-py310
          resources:
            requests:
              cpu: "1"
              memory: "1.5Gi"
          volumeMounts:
          - name: script-volume
            mountPath: /app
        volumes:
        - name: script-volume
          configMap:
            name: churn-processing-script